# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; use os.pathsep
# to specify multiple locations in Windows
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# leave blank for local time
# timezone =

# max length of characters to prepend to revision identifiers
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc files to be created
# sourceless = false

# version location specification; This defaults
# to alembic/versions.  When using multiple version
# directories, initial revisions must be specified with --version-path
# version_locations = %(here)s/bar:%(here)s/bat:alembic/versions

# version path separator; defaults to os.pathsep.
# Use os.pathsep to specify multiple locations in Windows
# version_path_separator = :

# set to 'true' to search source files recursively
# recursive_version_locations = false

# the output encoding used when revision files
# are written from script.py.mako
# output_encoding = utf-8

sqlalchemy.url = postgresql+asyncpg://postgres:postgres@db:5432/app


[post_write_hooks]
# post_write_hooks allows scripts to be run after generating a revision file
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = REVISION_SCRIPT_FILENAME

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
