"""add_thinking_log_to_review

Revision ID: 5faa2816fbe1
Revises: f3e1a7b8c9d0
Create Date: 2026-05-22 05:14:07.877736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5faa2816fbe1'
down_revision = 'f3e1a7b8c9d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('thinking_log', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'thinking_log')
    # ### end Alembic commands ###
