"""add_llm_config_to_user

Revision ID: dc34b3a3b636
Revises: 5faa2816fbe1
Create Date: 2026-05-23 08:05:26.619461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc34b3a3b636'
down_revision = '5faa2816fbe1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('llm_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'llm_config')
    # ### end Alembic commands ###
